from __future__ import annotations

from .audio import (
    AudioBackendError,
    AudioBackendStatus,
    MissingVoiceDependency,
    check_voice_dependencies,
    ensure_voice_playback_dependencies,
    iter_file_chunks,
    iter_opus_frames,
    iter_pcm_s16le_frames,
)
from .connection import (
    FATAL_VOICE_CLOSE_CODES,
    REJOIN_VOICE_CLOSE_CODES,
    VoiceCloseAction,
    VoiceConnection,
    VoiceManager,
    classify_voice_close_code,
)
from .crypto import (
    VoiceBox,
    VoiceDecryptionError,
    create_voice_box,
    supported_encryption_modes,
)
from .dave import (
    DaveBackendError,
    DaveCommit,
    DaveCryptoBackend,
    DaveCryptoError,
    DaveError,
    DaveKeyPackage,
    DaveMLSError,
    DaveOpcode,
    DaveOutboundPayload,
    DavePayloadError,
    DaveProtocolController,
    DaveProtocolState,
    DaveSenderInfo,
    DaveTransition,
    DaveUnsupportedError,
    ReferenceDaveBackend,
    UnsupportedDaveBackend,
)
from .models import (
    VoiceEncryptionMode,
    VoiceGatewayConfig,
    VoiceReady,
    VoiceServerUpdate,
    VoiceSessionDescription,
    VoiceSpeakingFlag,
    VoiceState,
)
from .player import AudioPlayer
from .receive import (
    AudioSink,
    BufferSink,
    CallbackSink,
    VoiceFrame,
    VoiceReceiver,
    WaveSink,
)
from .rtp import RTPPacket, is_rtcp_packet, parse_rtp_packet
from .sources import (
    AudioSource,
    FFmpegOpusAudio,
    FFmpegPCMAudio,
    OpusFrameSource,
    PCMAudio,
    PCMVolumeTransformer,
    SilenceSource,
)
from .udp import (
    VoiceDatagram,
    VoiceUDPClient,
    build_ip_discovery_packet,
    parse_ip_discovery_response,
)

__all__ = [
    "AudioPlayer",
    "AudioSink",
    "AudioSource",
    "BufferSink",
    "CallbackSink",
    "FATAL_VOICE_CLOSE_CODES",
    "FFmpegOpusAudio",
    "FFmpegPCMAudio",
    "OpusFrameSource",
    "PCMAudio",
    "PCMVolumeTransformer",
    "REJOIN_VOICE_CLOSE_CODES",
    "RTPPacket",
    "SilenceSource",
    "VoiceBox",
    "VoiceCloseAction",
    "VoiceConnection",
    "VoiceDecryptionError",
    "VoiceFrame",
    "VoiceReceiver",
    "WaveSink",
    "classify_voice_close_code",
    "create_voice_box",
    "is_rtcp_packet",
    "parse_rtp_packet",
    "supported_encryption_modes",
    "VoiceEncryptionMode",
    "VoiceGatewayConfig",
    "VoiceManager",
    "DaveBackendError",
    "DaveCommit",
    "DaveCryptoBackend",
    "DaveCryptoError",
    "DaveError",
    "DaveKeyPackage",
    "DaveMLSError",
    "DaveOpcode",
    "DaveOutboundPayload",
    "DavePayloadError",
    "DaveProtocolController",
    "DaveProtocolState",
    "DaveSenderInfo",
    "DaveTransition",
    "DaveUnsupportedError",
    "ReferenceDaveBackend",
    "UnsupportedDaveBackend",
    "VoiceReady",
    "VoiceSpeakingFlag",
    "VoiceServerUpdate",
    "VoiceSessionDescription",
    "VoiceState",
    "VoiceDatagram",
    "VoiceUDPClient",
    "AudioBackendError",
    "AudioBackendStatus",
    "MissingVoiceDependency",
    "check_voice_dependencies",
    "ensure_voice_playback_dependencies",
    "iter_file_chunks",
    "iter_pcm_s16le_frames",
    "iter_opus_frames",
    "build_ip_discovery_packet",
    "parse_ip_discovery_response",
]
