from __future__ import annotations

from .audio import (
    AudioBackendError,
    AudioBackendStatus,
    MissingVoiceDependency,
    check_voice_dependencies,
    ensure_voice_playback_dependencies,
    iter_file_chunks,
    iter_opus_frames,
    iter_pcm_s16le_frames,
)
from .connection import VoiceConnection, VoiceManager
from .dave import (
    DaveBackendError,
    DaveCommit,
    DaveCryptoBackend,
    DaveKeyPackage,
    DaveOpcode,
    DaveOutboundPayload,
    DavePayloadError,
    DaveProtocolController,
    DaveProtocolState,
    DaveTransition,
    DaveUnsupportedError,
    UnsupportedDaveBackend,
)
from .models import (
    VoiceEncryptionMode,
    VoiceGatewayConfig,
    VoiceReady,
    VoiceServerUpdate,
    VoiceSessionDescription,
    VoiceSpeakingFlag,
    VoiceState,
)
from .udp import (
    VoiceDatagram,
    VoiceUDPClient,
    build_ip_discovery_packet,
    parse_ip_discovery_response,
)

__all__ = [
    "VoiceConnection",
    "VoiceEncryptionMode",
    "VoiceGatewayConfig",
    "VoiceManager",
    "DaveBackendError",
    "DaveCommit",
    "DaveCryptoBackend",
    "DaveKeyPackage",
    "DaveOpcode",
    "DaveOutboundPayload",
    "DavePayloadError",
    "DaveProtocolController",
    "DaveProtocolState",
    "DaveTransition",
    "DaveUnsupportedError",
    "UnsupportedDaveBackend",
    "VoiceReady",
    "VoiceSpeakingFlag",
    "VoiceServerUpdate",
    "VoiceSessionDescription",
    "VoiceState",
    "VoiceDatagram",
    "VoiceUDPClient",
    "AudioBackendError",
    "AudioBackendStatus",
    "MissingVoiceDependency",
    "check_voice_dependencies",
    "ensure_voice_playback_dependencies",
    "iter_file_chunks",
    "iter_pcm_s16le_frames",
    "iter_opus_frames",
    "build_ip_discovery_packet",
    "parse_ip_discovery_response",
]
