"""
VaidCord - High-performance Discord framework inspired by Aiogram 3.x architecture.

This package provides a modern, type-safe, and performant way to build Discord bots
with full support for Python 3.12+.

Features:
- Modern async/await API
- Type-safe event handling
- Comprehensive formatting utilities
- HTTP client with proxy support
- Advanced mocking for testing
- Custom API endpoints
- Full OAuth2 support with user authentication
"""

from __future__ import annotations

from vaidcord.metadata import __author__, __version__

# Lazy imports to avoid circular dependency issues
__lazy_imports__ = {
    "Bot": ".bot",
    "BotConfig": ".bot",
    "BotState": ".bot",
    "GatewayIntent": ".bot",
    "Router": ".router",
    "Dispatcher": ".dispatcher",
    "Application": ".application",
    "ApplicationRoleConnectionMetadata": ".application",
    "ApplicationRoleConnectionMetadataType": ".application",
    "Middleware": ".typing",
    "NextHandler": ".typing",
    "EventHandler": ".typing",
    "EventHandlerResult": ".typing",
    "LifecycleHandler": ".router",
    "RouterFilterConfig": ".router",
    "BaseMiddleware": ".middleware",
    # Filters
    "F": ".filters",
    "FilterExpr": ".filters",
    "MagicFilter": ".filters",
    "CustomFilter": ".filters",
    "CommandFilter": ".filters",
    "CommandStartFilter": ".filters",
    "CommandHelpFilter": ".filters",
    "CommandSettingsFilter": ".filters",
    "RegexFilter": ".filters",
    "UserFilter": ".filters",
    "Event": ".types",
    "EventType": ".types",
    "WebhookEventType": ".types",
    "Message": ".types",
    "Ready": ".types",
    "Resume": ".types",
    "Reaction": ".types",
    "TypingStart": ".types",
    "PollVote": ".types",
    "DeletedMessage": ".types",
    "BulkDeletedMessages": ".types",
    "MessagePin": ".types",
    "RawGatewayEvent": ".types",
    "User": ".types",
    "Guild": ".types",
    "Channel": ".types",
    "Formatter": ".formatting",
    "HTTPClient": ".http",
    "HTTPConfig": ".http",
    "DiscordError": ".http",
    "MockBot": ".mock",
    "MockSettings": ".mock",
    "MockGateway": ".mock",
    "MockHTTPClient": ".mock",
    "create_mock_message": ".mock",
    "create_mock_event": ".mock",
    # OAuth2
    "OAuth2Client": ".oauth2",
    "UserAuthClient": ".oauth2",
    "OAuth2Config": ".oauth2",
    "OAuth2Token": ".oauth2",
    "OAuth2Scope": ".oauth2",
    "OAuth2Error": ".oauth2",
    "IntegrationType": ".oauth2",
    "PromptType": ".oauth2",
    # Errors
    "VaidCordError": ".errors",
    "DiscordAPIError": ".errors",
    "GatewayError": ".errors",
    "VoiceGatewayError": ".errors",
    "RateLimitError": ".errors",
    "AuthenticationError": ".errors",
    "ForbiddenError": ".errors",
    "NotFoundError": ".errors",
    "ValidationError": ".errors",
    "MissingPermissions": ".errors",
    "HierarchyError": ".errors",
    "GatewayOpcode": ".errors",
    "GatewayCloseCode": ".errors",
    "VoiceGatewayOpcode": ".errors",
    "VoiceGatewayCloseCode": ".errors",
    "DiscordErrorCode": ".errors",
    "create_discord_error": ".errors",
    "create_gateway_error": ".errors",
    "create_voice_gateway_error": ".errors",
    # Logging
    "configure_logging": ".logging",
    "LogConfig": ".logging",
    "LogFileConfig": ".logging",
    "get_logger": ".logging",
    # Permissions
    "Permissions": ".permissions",
    "PermissionOverwrite": ".permissions",
    "PermissionCalculator": ".permissions",
    "calculate_permissions": ".permissions",
    "check_permission": ".permissions",
    # FSM
    "FSMContext": ".fsm",
    "FSMManager": ".fsm",
    "FSMScope": ".fsm",
    "FSMMiddleware": ".fsm",
    "MemoryFSMStorage": ".fsm",
    "SQLiteFSMStorage": ".fsm",
    "RedisFSMStorage": ".fsm",
    "MongoFSMStorage": ".fsm",
    "PostgresFSMStorage": ".fsm",
    "StateValue": ".fsm",
    "StorageKey": ".fsm",
    "BaseFSMStorage": ".fsm",
    "State": ".fsm",
    "StatesGroup": ".fsm",
    # Voice
    "VoiceConnection": ".voice",
    "VoiceEncryptionMode": ".voice",
    "VoiceSpeakingFlag": ".voice",
    "VoiceGatewayConfig": ".voice",
    "VoiceManager": ".voice",
    "VoiceReady": ".voice",
    "VoiceServerUpdate": ".voice",
    "VoiceSessionDescription": ".voice",
    "VoiceState": ".voice",
    "VoiceDatagram": ".voice",
    "VoiceUDPClient": ".voice",
    "DaveBackendError": ".voice",
    "DaveCommit": ".voice",
    "DaveCryptoBackend": ".voice",
    "DaveCryptoError": ".voice",
    "DaveError": ".voice",
    "DaveKeyPackage": ".voice",
    "DaveMLSError": ".voice",
    "DaveOpcode": ".voice",
    "DaveOutboundPayload": ".voice",
    "DavePayloadError": ".voice",
    "DaveProtocolController": ".voice",
    "DaveProtocolState": ".voice",
    "DaveSenderInfo": ".voice",
    "DaveTransition": ".voice",
    "DaveUnsupportedError": ".voice",
    "ReferenceDaveBackend": ".voice",
    "UnsupportedDaveBackend": ".voice",
    "iter_file_chunks": ".voice",
    "iter_pcm_s16le_frames": ".voice",
    "iter_opus_frames": ".voice",
    "AudioBackendError": ".voice",
    "AudioBackendStatus": ".voice",
    "MissingVoiceDependency": ".voice",
    "check_voice_dependencies": ".voice",
    "ensure_voice_playback_dependencies": ".voice",
    "IS_COMPONENTS_V2": ".components",
    "ButtonStyle": ".components",
    "ComponentType": ".components",
    "action_row": ".components",
    "button": ".components",
    "checkbox": ".components",
    "components_v2_message": ".components",
    "container": ".components",
    "file_component": ".components",
    "label": ".components",
    "media_gallery": ".components",
    "media_item": ".components",
    "modal_payload": ".components",
    "section": ".components",
    "select_menu": ".components",
    "select_option": ".components",
    "separator": ".components",
    "text_display": ".components",
    "text_input": ".components",
    "thumbnail": ".components",
    "ApplicationCommandType": ".commands",
    "CommandContext": ".commands",
    "RegisteredCommand": ".commands",
}


def __getattr__(name: str):
    if name in __lazy_imports__:
        import importlib

        module_path = __lazy_imports__[name]
        module = importlib.import_module(module_path, package="vaidcord")
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    # Core
    "Bot",
    "BotConfig",
    "Router",
    "Dispatcher",
    "Application",
    "ApplicationRoleConnectionMetadata",
    "ApplicationRoleConnectionMetadataType",
    "Middleware",
    "NextHandler",
    "EventHandler",
    "EventHandlerResult",
    "LifecycleHandler",
    "RouterFilterConfig",
    "BaseMiddleware",
    "F",
    "FilterExpr",
    "MagicFilter",
    "CustomFilter",
    "CommandFilter",
    "CommandStartFilter",
    "CommandHelpFilter",
    "CommandSettingsFilter",
    "RegexFilter",
    "UserFilter",
    "BotState",
    "GatewayIntent",
    # Types
    "Event",
    "EventType",
    "WebhookEventType",
    "Message",
    "Ready",
    "Resume",
    "Reaction",
    "TypingStart",
    "PollVote",
    "DeletedMessage",
    "BulkDeletedMessages",
    "MessagePin",
    "RawGatewayEvent",
    "User",
    "Guild",
    "Channel",
    # Formatting
    "Formatter",
    # HTTP
    "HTTPClient",
    "HTTPConfig",
    "DiscordError",
    # Mocking
    "MockBot",
    "MockSettings",
    "MockGateway",
    "MockHTTPClient",
    "create_mock_message",
    "create_mock_event",
    # OAuth2
    "OAuth2Client",
    "UserAuthClient",
    "OAuth2Config",
    "OAuth2Token",
    "OAuth2Scope",
    "OAuth2Error",
    "IntegrationType",
    "PromptType",
    # Errors
    "VaidCordError",
    "DiscordAPIError",
    "GatewayError",
    "VoiceGatewayError",
    "RateLimitError",
    "AuthenticationError",
    "ForbiddenError",
    "NotFoundError",
    "ValidationError",
    "MissingPermissions",
    "HierarchyError",
    "GatewayOpcode",
    "GatewayCloseCode",
    "VoiceGatewayOpcode",
    "VoiceGatewayCloseCode",
    "DiscordErrorCode",
    "create_discord_error",
    "create_gateway_error",
    "create_voice_gateway_error",
    # Logging
    "configure_logging",
    "LogConfig",
    "LogFileConfig",
    "get_logger",
    # Permissions
    "Permissions",
    "PermissionOverwrite",
    "PermissionCalculator",
    "calculate_permissions",
    "check_permission",
    # FSM
    "FSMContext",
    "FSMManager",
    "FSMScope",
    "FSMMiddleware",
    "MemoryFSMStorage",
    "SQLiteFSMStorage",
    "RedisFSMStorage",
    "MongoFSMStorage",
    "PostgresFSMStorage",
    "StateValue",
    "StorageKey",
    "BaseFSMStorage",
    "State",
    "StatesGroup",
    # Voice
    "VoiceConnection",
    "VoiceEncryptionMode",
    "VoiceSpeakingFlag",
    "VoiceGatewayConfig",
    "VoiceManager",
    "VoiceReady",
    "VoiceServerUpdate",
    "VoiceSessionDescription",
    "VoiceState",
    "VoiceDatagram",
    "VoiceUDPClient",
    "DaveBackendError",
    "DaveCommit",
    "DaveCryptoBackend",
    "DaveCryptoError",
    "DaveError",
    "DaveKeyPackage",
    "DaveMLSError",
    "DaveOpcode",
    "DaveOutboundPayload",
    "DavePayloadError",
    "DaveProtocolController",
    "DaveProtocolState",
    "DaveSenderInfo",
    "DaveTransition",
    "DaveUnsupportedError",
    "ReferenceDaveBackend",
    "UnsupportedDaveBackend",
    "AudioBackendError",
    "AudioBackendStatus",
    "MissingVoiceDependency",
    "check_voice_dependencies",
    "ensure_voice_playback_dependencies",
    "iter_file_chunks",
    "iter_pcm_s16le_frames",
    "iter_opus_frames",
    "IS_COMPONENTS_V2",
    "ButtonStyle",
    "ComponentType",
    "action_row",
    "button",
    "checkbox",
    "components_v2_message",
    "container",
    "file_component",
    "label",
    "media_gallery",
    "media_item",
    "modal_payload",
    "section",
    "select_menu",
    "select_option",
    "separator",
    "text_display",
    "text_input",
    "thumbnail",
    "ApplicationCommandType",
    "CommandContext",
    "RegisteredCommand",
    # Version
    "__author__",
    "__version__",
]
